[package]
name = "jitsi-openid"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19", features = ["macros", "rt-multi-thread", "signal"], default-features = false }
openidconnect = { git = "https://github.com/MarcelCoding/openidconnect-rs", features = ["reqwest", "rustls-tls"], default-features = false } # version = "2.3"
axum = { version = "0.5", features = ["http1", "query", "headers", "form"], default-features = false } # TODO: remove form
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.1", features = ["v4"] }
axum-extra = {version ="0.3", features=["cookie"]}
tracing-subscriber = "0.3"
jsonwebtoken = "8.1"
tracing = "0.1"
cookie = "0.16"
config = "0.13"
anyhow = "1.0"
time = "0.3"
url = "2.2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

# by overriding our dependencies' compilation settings, we can further optimize for size
# https://docs.rust-embedded.org/book/unsorted/speed-vs-size.html#optimizing-dependencies
[profile.release.package."*"]
codegen-units = 1
